---
- hosts: localhost
  tasks:
    - name: Provision EC2 instance
      ec2:
         region: us-east-1
         instance_type: t2.micro
         image: ami-062f7200baf2fa504
         wait: yes
         wait_timeout: 500
         count: 1
         instance_tags:
            Name: AWS-Ansible
         volumes:
            - device_name: /dev/xvda
              volume_type: gp2
              volume_size: 8
         monitoring: yes
      register: ec2
    - name: create VPC
      ec2_vpc_net:
         name: Ansible VPC
         cidr_block: 10.10.0.0/24
         region: us-east-1
         state: present
      register: vpc
    - name: associate subnet to the VPC
      ec2_vpc_subnet:
         state: present
         vpc_id: Ansible VPC
         region: us-east-1
         cidr: 10.10.0.0/26
         map_public: yes
         resource_tags:
            Name: Ansible Subnet
      register: subnet
